### ISSUE TITLE
arxiv link of RandAugment is wrong

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [CrazyVertigo/awesome-data-augmentation#2]
arxiv link of paper "RandAugment: Practical automated data augmentation with a reduced search space" is wrong, which should be [https://arxiv.org/pdf/1909.13719.pdf](https://arxiv.org/pdf/1909.13719.pdf)

**Comment by CrazyVertigo** [comment]
Thanks. I have fixed it.

**Comment by CrazyVertigo** [comment]
> arxiv link of paper "RandAugment: Practical automated data augmentation with a reduced search space" is wrong, which should be https://arxiv.org/pdf/1909.13719.pdf

Thanks. I have fixed it.
